---
name: Bug Report
about: Report a bug or unexpected behavior
labels: ["bug"]
assignees: []
---

## Bug Description

Please describe the bug you encountered in as much detail as possible.

- What happened?
- What did you expect to happen?
- Are there any error messages shown?

## Steps to Reproduce

1.
2.
3.
4.

_(Please include exact steps so we can reproduce the issue.)_

## Screenshots / Logs

If applicable, add screenshots or logs to help explain your problem.

## Environment

| Feature | Details |
|---------|---------|
| OS | |
| Datary Version | |
| Database | |

## Additional Context

Add any other context about the problem here.
