name: Bug Report
description: Report a bug or unexpected behavior
labels: ['bug']
assignees: []

body:
    - type: textarea
      attributes:
          label: Bug Description
          description: |
              Please describe the bug you encountered in as much detail as possible.

              - What happened?
              - What did you expect to happen?
              - Are there any error messages shown?
          placeholder: |
              Describe the bug clearly and concisely.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps to Reproduce
          description: |
              Please include exact steps so we can reproduce the issue.
          placeholder: |
              1.
              2.
              3.
              4.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots / Logs
          description: |
              If applicable, add screenshots or logs to help explain your problem.
          placeholder: |
              Paste logs here or attach screenshots.

    - type: markdown
      attributes:
          value: |
              ## Environment

    - type: input
      attributes:
          label: OS
          placeholder: macOS / Windows / Linux
      validations:
          required: true

    - type: input
      attributes:
          label: Datary Version
          placeholder: 0.0.1
      validations:
          required: true

    - type: input
      attributes:
          label: Database
          placeholder: PostgreSQL / MySQL / MariaDB / Microsoft SQL Server
      validations:
          required: true

    - type: textarea
      attributes:
          label: Additional Context
          description: |
              Add any other context about the problem here.
          placeholder: |
              Any extra information that may help.
